### ISSUE TITLE
PostCSS with SapperJs and TailwindCSS

### ISSUE THREAD

**Issue by ansarizafar** [TehShrike/svelte-preprocess-postcss#1]
I want to use TailwindCSS with SapperJs and remove unused css classes. Is it possible to use svelte-preprocess-postcss with Sapper. Is there any example available?

**Comment by TehShrike** [comment]
Looks like there are a few PostCSS plugins that claim to do that https://www.postcss.parts/?searchTerm=unused

Otherwise, I'm not sure how TailwindCSS specifically relates to this, unless you want to look at the source code to figure out how to make your own Tailwind preprocessor.  It's relatively simple.
